# Generated by Django 4.2 on 2023-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='time_slot',
            field=models.CharField(choices=[('MORNING', '8 AM to 12 PM'), ('AFTERNOON', '12 PM to 6 PM'), ('EVENING', '6 PM to 12 AM')], default='MORNING', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('date', 'slot_number', 'time_slot')},
        ),
    ]
