# Generated by Django 4.2 on 2023-04-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_parkingslot_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='rates',
            field=models.ManyToManyField(related_name='parking_slots', to='api_v1.parkingrate'),
        ),
    ]
